#!/bin/sh
# Ensure boot configuration is updated when initrd is updated 

PREREQ=""
prereqs()
{
     echo "$PREREQ"
}

case $1 in
   prereqs)
       prereqs
       exit 0
       ;;
esac

. /usr/share/initramfs-tools/hook-functions

/usr/bin/update-boot
